### ISSUE TITLE
No module named 'saliency_models'

### ISSUE THREAD

**Issue by little4git** [shreelock/gbvs#2]
Hi all,
I tried the example but got this exception.

Is there anything wrong with the build-up?

**Comment by shreelock** [comment]
You might have some issue with the python path, which is why this error is coming. Make sure that you are running the script from the root folder. Otherwise, add it to your path before running. 

There isn't anything getting built as such. Just modules getting imported

**Comment by shreelock** [comment]
Closing the issue.
