### ISSUE TITLE
GBVS map overlayed

### ISSUE THREAD

**Issue by n3urovirtual** [shreelock/gbvs#6]
Hi. Does your package support the computation of a **GBVS map overlayed image** as shown below: 

![image](https://user-images.githubusercontent.com/67779935/122397927-116d3580-cf82-11eb-8a93-afaf4c093e88.png)

Thanks.

**Comment by shreelock** [comment]
It doesn't, for now. But I believe this functionality can be easily added. I do not have time for it now, but feel free to contribute.

**Comment by Adibuoy23** [comment]
Hi, Check this out for overlaying heatmaps! 

https://github.com/LinShanify/HeatMap

I found this code to do that same thing
