### ISSUE TITLE
Are images in BMP format available？

### ISSUE THREAD

**Issue by ssli23** [shreelock/gbvs#7]
When trying to run an image in BMP format, an error occurs, as follows:
Value error：Input contains NaN，infinity or a value too large for dtype（‘float64’）

**Comment by shreelock** [comment]
As you might notice, we are using cv2 imread to read the images. With PNGs and other commonly supported file formats, this leads the output to be a 3D matrix with values ranging from 0,255. I suggest if you are trying to read BMP images, please verify the values of the matrix that gets generated upon cv2 imread is in the same range. You might have to scale values up/down if thats not the case.
